### ISSUE TITLE
[Issue]: Repetition of previous images on every new image in a normal batch.

### ISSUE THREAD

**Issue by itzolkmar** [vladmandic/sdnext#4084]
### Issue Description

This means if you run a batch of 4 images you get #1, then #1 and #2, then #1 and #2 and #3, then #1 and #2 and #3 and #4. That means we have 10 images in total containing 6 duplicate images. That happens in t2i and in i2i.

SD_SAVE_DEBUG was set. You see the image savings in the log.

### Version Platform Description

Last Version, Win11, NVIDIA GeForce RTX 5090

[repetitions.log](https://github.com/user-attachments/files/21519879/repetitions.log)

### Relevant log output

```shell

```

### Backend

Diffusers

### Compute

nVidia CUDA

### Interface

Standard

### Branch

Master

### Model

StableDiffusion 3.x

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by rafarvns** [comment]
same problem here. do you have a alternative solution for this?

**Comment by fnordKL** [comment]
same problem here. numerous dublicates are created when batch is done.

**Comment by itzolkmar** [comment]
I still use the version from end of June. I think it will not take long till Vlado has solved it. Nothing complicated.

**Comment by vladmandic** [comment]
yes, there was an issue on 07/29 version and it was fixed the next day and i've published a refresh.
even your log says there is a new version available:

<img width="1039" height="41" alt="Image" src="https://github.com/user-attachments/assets/15a258a4-0334-4ce5-b37c-259ecfbc7681" />

**Comment by rafarvns** [comment]
> yes, there was an issue on 07/29 version and it was fixed the next day and i've published a refresh. even your log says there is a new version available:
> <img alt="Image" width="1039" height="41" src="https://private-user-images.githubusercontent.com/57876960/472971570-15a258a4-0334-4ce5-b37c-259ecfbc7681.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM5NjQ0NTksIm5iZiI6MTc1Mzk2NDE1OSwicGF0aCI6Ii81Nzg3Njk2MC80NzI5NzE1NzAtMTVhMjU4YTQtMDMzNC00Y2U1LWIzN2MtMjU5ZWNmYmM3NjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzMxVDEyMTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZjg5YTgwNzM4MWIwMzAwYzJlNWRkMWNiOGQzMDI3OWNkODBmZGU5YWI2YzUxZGMyMTkzY2Y5NDk3OWYxOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6-Y-z6jiCXA3YwAG-RDaP2eTEGavKmtuEJ489oHEsHw">


im using the  < updated=2025-07-31 hash=fd060e8f branch=master > version, and the problem persist
[repetitions_log.txt](https://github.com/user-attachments/files/21530337/repetitions_log.txt)

**Comment by vladmandic** [comment]
ok, reopening, will be fixed today.
@rafarvns just to verify, walk me through your params

**Comment by rafarvns** [comment]
> ok, reopening, will be fixed today. [@rafarvns](https://github.com/rafarvns) just to verify, walk me through your params

What exactly do you need? I'm still starting out in this field.
I've attached some screenshots that I think might be relevant. If not, and could you explain them to me, please.

screenshots -> https://imgur.com/a/fmqF5wa

**Comment by itzolkmar** [comment]
I've got the latest version a few minutes ago. Same problem.

[sdnext.log](https://github.com/user-attachments/files/21531245/sdnext.log)

**Comment by vladmandic** [comment]
yes, found it and fixed in dev branch, my appologies.
i'll do a master refresh by eob.

**Comment by itzolkmar** [comment]
Great, thanks. Looking forward to use the Modern UI. :-)

**Comment by vladmandic** [comment]
update posted, let me know if there are any more related issues

**Comment by itzolkmar** [comment]
Thanks, Vlado. There's still a little problem. The good thing is that the duplicates have disappeared and I can see a preview image again – at least with SD3. However, there is currently one disadvantage, especially with larger batches: the images are only saved after the entire batch has been processed. This was a little more user-friendly before. For example, you could look at the current results via the network. Or you could already process individual results. If you frequently have batches of 50 or 100 images, this is of course a bit inconvenient. For people with less RAM, this could also cause problems, and the timestamps that I include in the file names no longer indicate the calculation times for the individual images, as they all represent approximately the same time of saving.
It's good that when the process is stopped, the images that have been calculated up to that point are saved.

The other problem is, that metadata are completely inconsistent. I just used wildcards, where each image has a completely different prompt. The parameters (prompt, seed etc.) of the last image was dumped to all images - in the name and the metadata. 

Here's the log and a screenshot of the resulting images:

[sdnext.log](https://github.com/user-attachments/files/21547738/sdnext.log)

![Image](https://github.com/user-attachments/assets/85debd97-0a9d-440e-a176-9d1ff6a2ff9d)

**Comment by vladmandic** [comment]
ah, leftover bugs due to removal of all of the legacy code.
i just refactored internal loop that runs after processing - new code is in dev branch if you can test.
once confirmed, i'll merge to master.

**Comment by itzolkmar** [comment]
Nearly fantastic! :-)
There's still the wrong '[seed]' in filename (fixed value that represents the first seed in the batch). In Metadata it's correct! Everything else regarding this issue seems to work as it should. 
And let me say this: you do excellent work. And it is absolutely normal that such bugs occur. At least if one considers the speed of your progress! What a gift to the world! Thanks, Vlado!  (If you like, I'll test it again.)

[sdnext.log](https://github.com/user-attachments/files/21552044/sdnext.log)

![Image](https://github.com/user-attachments/assets/2785896d-6100-4634-97ff-db0f9870b678)

**Comment by vladmandic** [comment]
thanks for the feedback, much appriciated!
seed in fn namegen should now also be fixed.
i'll do a master refresh soon.
